### ISSUE TITLE
Enable and fix the inspector tests

### ISSUE THREAD

**Issue by kfarnung** [nodejs/node-chakracore#227]
The inspector tests are currently disabled.  Re-enable them and get them passing.

### New test cases
- [ ] Add a lambda paused event test case for #230 
- [ ] Add TTD stepback/reverse test cases for #244
- [ ] Add undefined variable test #280

**Comment by digitalinfinity** [comment]
@kfarnung what's left here?

**Comment by kfarnung** [comment]
I haven't gotten a chance to circle back and add some new tests yet.  The original item is complete though.
