### ISSUE TITLE
Tracking: Perf workitems 

### ISSUE THREAD

**Issue by aruneshchandra** [nodejs/node-chakracore#379]

**Comment by MSLaguana** [comment]
- [x] Further improve `JsCopyString` API and usage to avoid additional buffer allocations and copies. @MSLaguana
- [ ] Investigate changing our calling convention on linux x64 to match the standard calling convention. @penguinwizzard
- [ ] Improve handling of external data @obastemur

**Comment by MSLaguana** [comment]
- [ ] Improve performance of `JSON::Stringify` by changing some of its caching behavior https://github.com/Microsoft/ChakraCore/pull/3607

**Comment by digitalinfinity** [comment]
I've opened #383, #384, #385 and #386 to track these, so we can close this issue. For future perf items, please open separate issues on either Microsoft/ChakraCore or Nodejs/Node-ChakraCore
